version: 1

workflows:
  train:
    jobs:
      - name: shuttle-detection-training
        machine: A4000
        container: paperspace/gradient-pytorch:latest
        repo: "https://github.com/BillTheTsar/Shuttle-Detection-Model.git"
        command: |
          # Install dependencies
          pip install -r requirements.txt

          # Download dataset from Hugging Face into /storage/dataset
          python - <<'EOF'
          from huggingface_hub import snapshot_download
          snapshot_download(
              repo_id="BillTheTsar/shuttle-detection-dataset",
              local_dir="/storage/dataset",
              repo_type="dataset"
          )
          EOF

          # Start training
          python scripts/train_stage1.py --data-dir /storage/dataset
version: 1