on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  TrainModel:
    resources:
      instance-type: A4000-8C  # <-- Check exact type in Paperspace UI
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: paperspace/gradient-pytorch:latest
      script: |
        set -ex  # Exit on error and print all commands
        echo "=== Environment Info ==="
        pwd
        echo "=== Environment Variables ==="
        env
        echo "=== Checking repo mount ==="
        ls -al /inputs || { echo "No /inputs found"; exit 1; }
        ls -al /inputs/repo || { echo "Repo not found under /inputs/repo"; exit 1; }

        echo "=== Changing directory ==="
        cd /inputs/repo

        echo "=== Current directory contents ==="
        ls -R

        echo "=== Upgrading pip and installing dependencies ==="
        pip install --upgrade pip
        pip install -r requirements.txt huggingface_hub

        echo "=== Downloading dataset from Hugging Face ==="
        python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='BillTheTsar/shuttle-detection-dataset', local_dir='/storage/dataset', repo_type='dataset')"

        echo "=== Starting training script ==="
        python scripts/train_stage1.py --data-dir /storage/dataset
