jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: "{{ event.github.url }}"
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume

  TrainModel:
    uses: script@v1
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    resources:
      instance-type: A4000
    with:
      image: "paperspace/gradient-pytorch:latest"
      script: |
        set -e
        set -x
        cd /inputs/repo

        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install huggingface_hub

        echo "Downloading dataset from Hugging Face..."
        python3 - <<'EOF'
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id="BillTheTsar/shuttle-detection-dataset",
    local_dir="/storage/dataset",
    repo_type="dataset"
)
EOF

        echo "Starting training..."
        python3 scripts/train_stage1.py --data-dir /storage/dataset
