on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  TrainModel:
    resources:
      instance-type: A4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |
        set -ex  # Exit on error and print all commands
        echo "=== Environment Info ==="
        pwd
        echo "=== Environment Variables ==="
        env
        echo "=== Checking repo mount ==="
        ls -al /inputs || { echo "No /inputs found"; exit 1; }
        ls -al /inputs/repo || { echo "Repo not found under /inputs/repo"; exit 1; }

        cd /inputs/repo
        echo "Current working directory:"
        pwd
        echo "Listing contents:"
        ls -R
        echo "Installing dependencies..."
        pip install -r requirements.txt
        pip install huggingface_hub

        echo "Downloading dataset from Hugging Face..."
        python - <<'EOF'
        from huggingface_hub import snapshot_download
        snapshot_download(
            repo_id="BillTheTsar/shuttle-detection-dataset",
            local_dir="/storage/dataset",
            repo_type="dataset"
        )
        EOF

        echo "Starting training..."
        python scripts/train_stage1.py --data-dir /storage/dataset
      image: paperspace/gradient-pytorch:latest