on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url

  TrainModel:
    resources:
      instance-type: A4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |
        set -e
        set -x
        cd /inputs/repo

        echo "Installing dependencies..."
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install huggingface_hub

        echo "Downloading dataset from Hugging Face..."
        python3 - << 'EOF'
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id="BillTheTsar/shuttle-detection-dataset",
    local_dir="/storage/dataset",
    repo_type="dataset"
)
EOF

        echo "Starting training..."
        python3 scripts/train_stage1.py --data-dir /storage/dataset
      image: paperspace/gradient-pytorch:latest
